services:
  frontend:
    build: ./Frontend
    ports:
      - 4173:4173
    networks:
      - myNetwork
    depends_on:
      - backend
    restart: on-failure

  backend:
    build: ./Backend
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};TrustServerCertificate=True;
      - JWT__Issuer=${JWT_ISSUER}
      - JWT__Audience=${JWT_AUDIENCE}
      - JWT__SigningKey=${JWT_SIGNING_KEY}
      - AllowedHosts=*
    networks:
      - myNetwork
    depends_on:
      - mssql
    restart: on-failure

  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - 1433:1433
    networks:
      - myNetwork
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: on-failure

networks:
  myNetwork:

volumes:
  sqlserver_data:
