name: CI/CD Pipeline

on:
  push:
    branches:
      - main 
  pull_request:

env:
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USERID: ${{ secrets.DB_USERID }}
  SA_PASSWORD: ${{ secrets.SA_PASSWORD }}
  
  JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
  JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
  JWT_SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}
  
  AZURE_WEBAPP_NAME: Galerie
  AZURE_RESOURCE_GROUP: Dejan_Group
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/galerie:frontend
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/galerie:backend
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/galerie:database

      - name: Deploy to Azure App Services
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          resource-group: Dejan_Group
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/galerie:frontend
            ${{ secrets.DOCKER_HUB_USERNAME }}/galerie:backend
            ${{ secrets.DOCKER_HUB_USERNAME }}/galerie:database

      - name: Clean up Docker containers
        run: docker-compose down
