# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Galerie

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_f0916e6fc91542c58d3cddc5ecb3b4a9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9974747c41794e06a7df820f2ac30122 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f0916e6fc91542c58d3cddc5ecb3b4a9 }}/dejanbusi/galerie-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Galerie'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_50cff2322b8143d7ae99042b84cecea3 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f0916e6fc91542c58d3cddc5ecb3b4a9 }}/dejanbusi/galerie-frontend:${{ github.sha }}'