# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Galerie
 
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_302763ea2e4946129fa9f287bce7df4a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_72c1ceb1dc704155bf0694cd3d5ecb3b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_302763ea2e4946129fa9f287bce7df4a }}/dejanbusi/galerie:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Galerie'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5c78c0ee8afb4bd1a7ea0afc8760a89f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_302763ea2e4946129fa9f287bce7df4a }}/dejanbusi/galerie:${{ github.sha }}'
